"""Arithmetic-expression DPDA used by the NSPDA arithmetic-eval example.

The DPDA accepts the language of valid arithmetic expressions in an
*alternating* fashion, matching the data generated by
`setup_experiment.py` and the paper's intent (Figure 2, Section 4.1):
one or more digits, then one operator, then one or more digits, etc.,
followed by a `'#'` end-of-input marker.

States:
    q0  -- initial; expects a digit (start of first operand)
    q1  -- in operand, just read a digit; may continue digit run,
            transition to operator, or end on '#'
    q2  -- just read an operator; expects a digit (start of next operand)
    qF  -- accepting state, after '#'

Stack alphabet Gamma = Sigma cup {Z0}, with `Z0 = 'Z'` as the bottom
marker. Every transition pushes the input symbol on top of the
current stack top; the stack therefore records the expression in
top-down (right-to-left) order. Downstream evaluation is handled by
`setup_experiment.evaluate_expression` and operates on the predicted
string returned by `NSPDA.accept`, not on the stack -- this matches
the paper's reported behavior (stack is for *recording*, a separate
component evaluates).
"""

from automata.pda.dpda import DPDA

from nsa.alphabet import Alphabet, digits_and_operators_alphabet
from nsa.pda import PushdownAutomaton

END_MARKER: str = "#"
STACK_BOTTOM: str = "Z"

DIGITS: tuple[str, ...] = tuple(str(i) for i in range(10))
# Match the published CNN checkpoint's labeling: '%' is the legacy
#   division glyph (paper uses '/'; data labels use '%'). See
#   `digits_and_operators_alphabet` docstring.
OPERATORS: tuple[str, ...] = ("+", "-", "*", "%")


def arithmetic_pda_alphabet() -> Alphabet:
    """Input alphabet for the arithmetic DPDA: digits + operators + '#'.

    Indices 0-13 match the perception network's output (10 digits + 4
    operators); index 14 is the end marker `'#'`. Use
    `END_MARKER` for the symbol literal.
    """
    base = digits_and_operators_alphabet()
    return Alphabet(list(base) + [END_MARKER])


def _push_action(symbol: str, top: str) -> tuple[str, str]:
    """Stack action: push `symbol` on top of `top`, preserving `top`.

    Returns the automata-lib top-down push tuple `(symbol, top)`. The
    first element becomes the new stack top.
    """
    return (symbol, top)


def build_arithmetic_dpda() -> PushdownAutomaton:
    """Construct the alternating-expression DPDA wrapped as a `PushdownAutomaton`.

    Returns:
        A `PushdownAutomaton` over the alphabet returned by
        `arithmetic_pda_alphabet()`, accepting any expression matching
        the regex `[0-9]+([+\\-*%][0-9]+)*#` (one operand, optionally
        followed by `(operator, operand)` repetitions, terminated by
        `'#'`).
    """
    states = {"q0", "q1", "q2", "qF"}
    input_symbols = set(DIGITS) | set(OPERATORS) | {END_MARKER}
    stack_symbols = input_symbols | {STACK_BOTTOM}

    transitions: dict = {
        "q0": {},
        "q1": {},
        "q2": {},
    }

    # q0 on digit (any stack top) -> q1, push digit
    for d in DIGITS:
        transitions["q0"][d] = {}
        for gamma in stack_symbols:
            transitions["q0"][d][gamma] = ("q1", _push_action(d, gamma))

    # q1 on digit -> q1, push digit
    for d in DIGITS:
        transitions["q1"][d] = {}
        for gamma in stack_symbols:
            transitions["q1"][d][gamma] = ("q1", _push_action(d, gamma))

    # q1 on operator -> q2, push operator
    for op in OPERATORS:
        transitions["q1"][op] = {}
        for gamma in stack_symbols:
            transitions["q1"][op][gamma] = ("q2", _push_action(op, gamma))

    # q1 on '#' -> qF, push '#'
    transitions["q1"][END_MARKER] = {}
    for gamma in stack_symbols:
        transitions["q1"][END_MARKER][gamma] = (
            "qF",
            _push_action(END_MARKER, gamma),
        )

    # q2 on digit -> q1, push digit
    for d in DIGITS:
        transitions["q2"][d] = {}
        for gamma in stack_symbols:
            transitions["q2"][d][gamma] = ("q1", _push_action(d, gamma))

    dpda = DPDA(
        states=states,
        input_symbols=input_symbols,
        stack_symbols=stack_symbols,
        transitions=transitions,
        initial_state="q0",
        initial_stack_symbol=STACK_BOTTOM,
        final_states={"qF"},
        acceptance_mode="final_state",
    )
    return PushdownAutomaton(
        dpda,
        alphabet=arithmetic_pda_alphabet(),
    )
